disable TPU usage
Currently causing an error when provisioning a new cluster:

```
Error: googleapi: Error 400: Cloud TPU is only supported starting from version 1.9.3., badRequest
```